//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Gender_EN_Khac {
            get {
                return ResourceManager.GetString("Gender_EN_Khac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_EN_Nam {
            get {
                return ResourceManager.GetString("Gender_EN_Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_EN_Nu {
            get {
                return ResourceManager.GetString("Gender_EN_Nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string Gender_VI_Khac {
            get {
                return ResourceManager.GetString("Gender_VI_Khac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Gender_VI_Nam {
            get {
                return ResourceManager.GetString("Gender_VI_Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Gender_VI_Nu {
            get {
                return ResourceManager.GetString("Gender_VI_Nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO.
        /// </summary>
        internal static string GroupCustomer_EN_PRO {
            get {
                return ResourceManager.GetString("GroupCustomer_EN_PRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP.
        /// </summary>
        internal static string GroupCustomer_EN_VIP {
            get {
                return ResourceManager.GetString("GroupCustomer_EN_VIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá đẳng cấp.
        /// </summary>
        internal static string GroupCustomer_VI_PRO {
            get {
                return ResourceManager.GetString("GroupCustomer_VI_PRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đẳng cấp.
        /// </summary>
        internal static string GroupCustomer_VI_VIP {
            get {
                return ResourceManager.GetString("GroupCustomer_VI_VIP", resourceCulture);
            }
        }
    }
}
